### PR TITLE
Create Appcircle

### PR DESCRIPTION
**Pull request by eelifcelik**

### CODE REVIEW

**Review by zigsphere — APPROVED** [review]
LGTM. Thank you for your contribution!

**Comment by eelifcelik** [comment]
@zigsphere Hi, is there anything that I need to do for the merge?

**Comment by zigsphere** [comment]
Nope! Feel free to merge. If you don't have permission to, please let me know. Thanks again!

**Comment by eelifcelik** [comment]
You are welcome! But I don't have permission to merge so if you can do it I would appreciate :)

**Pull request merged**
